version: "2"

networks:
  smurf:

services: 
  fabric-ca-server:
    container_name: fabric-ca-server
    image: hyperledger/fabric-ca:1.4
    restart: always
    ports:
      - "7054:7054"
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    volumes:
      - "./castorage:/etc/hyperledger/fabric-ca-server"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    networks: 
      - smurf